name: students_reminder
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_auth: ^5.4.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7

  # UI and Navigation
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.3
  image_picker: ^1.2.0
  crop_your_image: ^2.0.0
  permission_handler: ^11.0.1
  intl: ^0.19.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  table_calendar: ^3.1.2
  geolocator: ^10.1.0
  google_maps_flutter: ^2.7.0
  geocoding: ^2.0.1 
  flutter_local_notifications: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  
