// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEoGvPJRV4d6Oh2RVuisxy-DRZUyp2M6Q',
    appId: '1:679398022451:web:1e880a3543f6115d83b246',
    messagingSenderId: '679398022451',
    projectId: 'reminder-5cb70',
    authDomain: 'reminder-5cb70.firebaseapp.com',
    storageBucket: 'reminder-5cb70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiqTS5f9ylWptsP89yHxYWaH0AQjGa35A',
    appId: '1:679398022451:android:1b8a8a68176f5c3083b246',
    messagingSenderId: '679398022451',
    projectId: 'reminder-5cb70',
    storageBucket: 'reminder-5cb70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqbuoXiEDUpRo_xG0_PSnudLkFfbaGrVk',
    appId: '1:679398022451:ios:c678bafb7af4e62183b246',
    messagingSenderId: '679398022451',
    projectId: 'reminder-5cb70',
    storageBucket: 'reminder-5cb70.firebasestorage.app',
    iosBundleId: 'com.example.studentRemeinderApp',
  );
}
